export interface PdfTextBlock {
  title?: string;
  lines: string[];
  accent?: boolean;
}

function escapePdfText(text: string): string {
  return text
    .replaceAll('\\', '\\\\')
    .replaceAll('(', String.raw`\(`)
    .replaceAll(')', String.raw`\)`)
    .replaceAll('\r', ' ')
    .replaceAll('\n', ' ');
}

function wrapLine(text: string, maxChars: number): string[] {
  if (text.length <= maxChars) {
    return [text];
  }

  const parts: string[] = [];
  let remaining = text;

  while (remaining.length > maxChars) {
    let breakIndex = remaining.lastIndexOf(' ', maxChars);
    if (breakIndex <= 0) {
      breakIndex = maxChars;
    }
    parts.push(remaining.slice(0, breakIndex).trim());
    remaining = remaining.slice(breakIndex).trimStart();
  }

  if (remaining) {
    parts.push(remaining);
  }

  return parts;
}

export function buildPdfBuffer(title: string, blocks: PdfTextBlock[]): Buffer {
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 36;
  const bodyWidth = pageWidth - margin * 2;
  const headerHeight = 94;
  const fontRegular = 4;
  const fontBold = 5;
  const pageTitleColor = '0.10 0.39 0.67 rg';
  const pageTitleTextColor = '1 1 1 rg';
  const bodyTextColor = '0.13 0.17 0.22 rg';
  const accentTextColor = '0.06 0.33 0.57 rg';
  const cardFill = '0.97 0.99 1 rg';
  const cardBorder = '0.80 0.88 0.95 RG';
  const maxChars = 90;

  const commands: string[] = [
    'q',
    '0.97 0.99 1 rg',
    `0 0 ${pageWidth} ${pageHeight} re f`,
    'Q',
    'q',
    pageTitleColor,
    `0 ${pageHeight - headerHeight} ${pageWidth} ${headerHeight} re f`,
    'Q',
    'BT',
    `/F${fontBold} 20 Tf`,
    pageTitleTextColor,
    `${margin} ${pageHeight - 54} Td`,
    `(${escapePdfText(title.toUpperCase())}) Tj`,
    `/F${fontRegular} 9 Tf`,
    `0 -18 Td`,
    `(${escapePdfText('Elvario.ch Auszahlungsschein')}) Tj`,
    'ET',
  ];

  let cursorY = pageHeight - headerHeight - 24;

  for (const block of blocks) {
    const titleText = block.title?.trim() || '';
    const wrappedLines = block.lines.flatMap((line) => wrapLine(line, maxChars));
    const linesHeight = wrappedLines.length * 14;
    const cardHeight = linesHeight + (titleText ? 36 : 20) + 18;
    const bottomY = cursorY - cardHeight;

    commands.push(
      'q',
      cardFill,
      `${margin} ${bottomY} ${bodyWidth} ${cardHeight} re f`,
      cardBorder,
      `${margin} ${bottomY} ${bodyWidth} ${cardHeight} re s`,
      'Q'
    );

    const headingY = cursorY - 22;
    if (titleText) {
      commands.push(
        'BT',
        `/F${fontBold} 12 Tf`,
        accentTextColor,
        `${margin + 16} ${headingY} Td`,
        `(${escapePdfText(titleText.toUpperCase())}) Tj`,
        'ET'
      );
    }

    let lineY = titleText ? headingY - 16 : cursorY - 18;
    for (const line of wrappedLines) {
      commands.push(
        'BT',
        `/F${fontRegular} 9.25 Tf`,
        bodyTextColor,
        `${margin + 16} ${lineY} Td`,
        `(${escapePdfText(line || ' ')}) Tj`,
        'ET'
      );
      lineY -= 14;
    }

    cursorY = bottomY - 14;
  }

  commands.push(
    'BT',
    `/F${fontRegular} 8.5 Tf`,
    '0.35 0.39 0.45 rg',
    `${margin} 24 Td`,
    `(${escapePdfText('Generated by Elvario.ch')}) Tj`,
    'ET'
  );

  const stream = commands.join('\n');
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    `3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F4 4 0 R /F5 5 0 R >> >> /Contents 6 0 R >> endobj`,
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    '5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj',
    `6 0 obj << /Length ${Buffer.byteLength(stream, 'utf8')} >> stream\n${stream}\nendstream endobj`,
  ];

  const header = '%PDF-1.4\n';
  const chunks: string[] = [header];
  const offsets: number[] = [0];
  let currentOffset = Buffer.byteLength(header, 'utf8');

  for (const object of objects) {
    offsets.push(currentOffset);
    chunks.push(`${object}\n`);
    currentOffset += Buffer.byteLength(`${object}\n`, 'utf8');
  }

  const xrefOffset = currentOffset;
  const xrefEntries = ['xref', '0 7', '0000000000 65535 f '];
  for (let i = 1; i < offsets.length; i += 1) {
    xrefEntries.push(`${offsets[i].toString().padStart(10, '0')} 00000 n `);
  }
  xrefEntries.push('trailer << /Size 7 /Root 1 0 R >>', 'startxref', String(xrefOffset), '%%EOF');

  chunks.push(xrefEntries.join('\n'));
  return Buffer.from(chunks.join(''), 'utf8');
}
